// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: backend/balance/v1/balance.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Balance_GetBalanceChanges_FullMethodName   = "/balance.Balance/GetBalanceChanges"
	Balance_GetRechargePayments_FullMethodName = "/balance.Balance/GetRechargePayments"
	Balance_GetRechargeManuals_FullMethodName  = "/balance.Balance/GetRechargeManuals"
	Balance_ConfirmPaymentOrder_FullMethodName = "/balance.Balance/ConfirmPaymentOrder"
	Balance_GetWithdraws_FullMethodName        = "/balance.Balance/GetWithdraws"
	Balance_GetWithdrawManuals_FullMethodName  = "/balance.Balance/GetWithdrawManuals"
	Balance_GetWithdrawReview_FullMethodName   = "/balance.Balance/GetWithdrawReview"
	Balance_DealWithWithdraw_FullMethodName    = "/balance.Balance/DealWithWithdraw"
	Balance_QueryUserBalance_FullMethodName    = "/balance.Balance/QueryUserBalance"
	Balance_QueryGameBalance_FullMethodName    = "/balance.Balance/QueryGameBalance"
	Balance_ManualUserBalance_FullMethodName   = "/balance.Balance/ManualUserBalance"
)

// BalanceClient is the client API for Balance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceClient interface {
	// 账变记录相关
	GetBalanceChanges(ctx context.Context, in *GetBalanceChangesReq, opts ...grpc.CallOption) (*GetBalanceChangesRes, error)
	// 充值记录相关
	GetRechargePayments(ctx context.Context, in *GetRechargePaymentsReq, opts ...grpc.CallOption) (*GetRechargePaymentsRes, error)
	GetRechargeManuals(ctx context.Context, in *GetRechargeManualsReq, opts ...grpc.CallOption) (*GetRechargeManualsRes, error)
	ConfirmPaymentOrder(ctx context.Context, in *ConfirmPaymentOrderReq, opts ...grpc.CallOption) (*ConfirmPaymentOrderRes, error)
	// 提现记录相关
	GetWithdraws(ctx context.Context, in *GetWithdrawsReq, opts ...grpc.CallOption) (*GetWithdrawsRes, error)
	GetWithdrawManuals(ctx context.Context, in *GetWithdrawManualsReq, opts ...grpc.CallOption) (*GetWithdrawManualsRes, error)
	GetWithdrawReview(ctx context.Context, in *GetWithdrawReviewReq, opts ...grpc.CallOption) (*GetWithdrawReviewRes, error)
	DealWithWithdraw(ctx context.Context, in *DealWithWithdrawReq, opts ...grpc.CallOption) (*DealWithWithdrawRes, error)
	// 余额查询和操作相关
	QueryUserBalance(ctx context.Context, in *QueryUserBalanceReq, opts ...grpc.CallOption) (*QueryUserBalanceRes, error)
	QueryGameBalance(ctx context.Context, in *QueryGameBalanceReq, opts ...grpc.CallOption) (*QueryGameBalanceRes, error)
	ManualUserBalance(ctx context.Context, in *ManualUserBalanceReq, opts ...grpc.CallOption) (*ManualUserBalanceRes, error)
}

type balanceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceClient(cc grpc.ClientConnInterface) BalanceClient {
	return &balanceClient{cc}
}

func (c *balanceClient) GetBalanceChanges(ctx context.Context, in *GetBalanceChangesReq, opts ...grpc.CallOption) (*GetBalanceChangesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceChangesRes)
	err := c.cc.Invoke(ctx, Balance_GetBalanceChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) GetRechargePayments(ctx context.Context, in *GetRechargePaymentsReq, opts ...grpc.CallOption) (*GetRechargePaymentsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRechargePaymentsRes)
	err := c.cc.Invoke(ctx, Balance_GetRechargePayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) GetRechargeManuals(ctx context.Context, in *GetRechargeManualsReq, opts ...grpc.CallOption) (*GetRechargeManualsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRechargeManualsRes)
	err := c.cc.Invoke(ctx, Balance_GetRechargeManuals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) ConfirmPaymentOrder(ctx context.Context, in *ConfirmPaymentOrderReq, opts ...grpc.CallOption) (*ConfirmPaymentOrderRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPaymentOrderRes)
	err := c.cc.Invoke(ctx, Balance_ConfirmPaymentOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) GetWithdraws(ctx context.Context, in *GetWithdrawsReq, opts ...grpc.CallOption) (*GetWithdrawsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawsRes)
	err := c.cc.Invoke(ctx, Balance_GetWithdraws_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) GetWithdrawManuals(ctx context.Context, in *GetWithdrawManualsReq, opts ...grpc.CallOption) (*GetWithdrawManualsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawManualsRes)
	err := c.cc.Invoke(ctx, Balance_GetWithdrawManuals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) GetWithdrawReview(ctx context.Context, in *GetWithdrawReviewReq, opts ...grpc.CallOption) (*GetWithdrawReviewRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawReviewRes)
	err := c.cc.Invoke(ctx, Balance_GetWithdrawReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) DealWithWithdraw(ctx context.Context, in *DealWithWithdrawReq, opts ...grpc.CallOption) (*DealWithWithdrawRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DealWithWithdrawRes)
	err := c.cc.Invoke(ctx, Balance_DealWithWithdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) QueryUserBalance(ctx context.Context, in *QueryUserBalanceReq, opts ...grpc.CallOption) (*QueryUserBalanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserBalanceRes)
	err := c.cc.Invoke(ctx, Balance_QueryUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) QueryGameBalance(ctx context.Context, in *QueryGameBalanceReq, opts ...grpc.CallOption) (*QueryGameBalanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGameBalanceRes)
	err := c.cc.Invoke(ctx, Balance_QueryGameBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) ManualUserBalance(ctx context.Context, in *ManualUserBalanceReq, opts ...grpc.CallOption) (*ManualUserBalanceRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManualUserBalanceRes)
	err := c.cc.Invoke(ctx, Balance_ManualUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceServer is the server API for Balance service.
// All implementations must embed UnimplementedBalanceServer
// for forward compatibility.
type BalanceServer interface {
	// 账变记录相关
	GetBalanceChanges(context.Context, *GetBalanceChangesReq) (*GetBalanceChangesRes, error)
	// 充值记录相关
	GetRechargePayments(context.Context, *GetRechargePaymentsReq) (*GetRechargePaymentsRes, error)
	GetRechargeManuals(context.Context, *GetRechargeManualsReq) (*GetRechargeManualsRes, error)
	ConfirmPaymentOrder(context.Context, *ConfirmPaymentOrderReq) (*ConfirmPaymentOrderRes, error)
	// 提现记录相关
	GetWithdraws(context.Context, *GetWithdrawsReq) (*GetWithdrawsRes, error)
	GetWithdrawManuals(context.Context, *GetWithdrawManualsReq) (*GetWithdrawManualsRes, error)
	GetWithdrawReview(context.Context, *GetWithdrawReviewReq) (*GetWithdrawReviewRes, error)
	DealWithWithdraw(context.Context, *DealWithWithdrawReq) (*DealWithWithdrawRes, error)
	// 余额查询和操作相关
	QueryUserBalance(context.Context, *QueryUserBalanceReq) (*QueryUserBalanceRes, error)
	QueryGameBalance(context.Context, *QueryGameBalanceReq) (*QueryGameBalanceRes, error)
	ManualUserBalance(context.Context, *ManualUserBalanceReq) (*ManualUserBalanceRes, error)
	mustEmbedUnimplementedBalanceServer()
}

// UnimplementedBalanceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceServer struct{}

func (UnimplementedBalanceServer) GetBalanceChanges(context.Context, *GetBalanceChangesReq) (*GetBalanceChangesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalanceChanges not implemented")
}
func (UnimplementedBalanceServer) GetRechargePayments(context.Context, *GetRechargePaymentsReq) (*GetRechargePaymentsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRechargePayments not implemented")
}
func (UnimplementedBalanceServer) GetRechargeManuals(context.Context, *GetRechargeManualsReq) (*GetRechargeManualsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRechargeManuals not implemented")
}
func (UnimplementedBalanceServer) ConfirmPaymentOrder(context.Context, *ConfirmPaymentOrderReq) (*ConfirmPaymentOrderRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPaymentOrder not implemented")
}
func (UnimplementedBalanceServer) GetWithdraws(context.Context, *GetWithdrawsReq) (*GetWithdrawsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithdraws not implemented")
}
func (UnimplementedBalanceServer) GetWithdrawManuals(context.Context, *GetWithdrawManualsReq) (*GetWithdrawManualsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithdrawManuals not implemented")
}
func (UnimplementedBalanceServer) GetWithdrawReview(context.Context, *GetWithdrawReviewReq) (*GetWithdrawReviewRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithdrawReview not implemented")
}
func (UnimplementedBalanceServer) DealWithWithdraw(context.Context, *DealWithWithdrawReq) (*DealWithWithdrawRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DealWithWithdraw not implemented")
}
func (UnimplementedBalanceServer) QueryUserBalance(context.Context, *QueryUserBalanceReq) (*QueryUserBalanceRes, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryUserBalance not implemented")
}
func (UnimplementedBalanceServer) QueryGameBalance(context.Context, *QueryGameBalanceReq) (*QueryGameBalanceRes, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryGameBalance not implemented")
}
func (UnimplementedBalanceServer) ManualUserBalance(context.Context, *ManualUserBalanceReq) (*ManualUserBalanceRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ManualUserBalance not implemented")
}
func (UnimplementedBalanceServer) mustEmbedUnimplementedBalanceServer() {}
func (UnimplementedBalanceServer) testEmbeddedByValue()                 {}

// UnsafeBalanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceServer will
// result in compilation errors.
type UnsafeBalanceServer interface {
	mustEmbedUnimplementedBalanceServer()
}

func RegisterBalanceServer(s grpc.ServiceRegistrar, srv BalanceServer) {
	// If the following call panics, it indicates UnimplementedBalanceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Balance_ServiceDesc, srv)
}

func _Balance_GetBalanceChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceChangesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).GetBalanceChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_GetBalanceChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).GetBalanceChanges(ctx, req.(*GetBalanceChangesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_GetRechargePayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRechargePaymentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).GetRechargePayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_GetRechargePayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).GetRechargePayments(ctx, req.(*GetRechargePaymentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_GetRechargeManuals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRechargeManualsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).GetRechargeManuals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_GetRechargeManuals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).GetRechargeManuals(ctx, req.(*GetRechargeManualsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_ConfirmPaymentOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).ConfirmPaymentOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_ConfirmPaymentOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).ConfirmPaymentOrder(ctx, req.(*ConfirmPaymentOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_GetWithdraws_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).GetWithdraws(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_GetWithdraws_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).GetWithdraws(ctx, req.(*GetWithdrawsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_GetWithdrawManuals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawManualsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).GetWithdrawManuals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_GetWithdrawManuals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).GetWithdrawManuals(ctx, req.(*GetWithdrawManualsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_GetWithdrawReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawReviewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).GetWithdrawReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_GetWithdrawReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).GetWithdrawReview(ctx, req.(*GetWithdrawReviewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_DealWithWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealWithWithdrawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).DealWithWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_DealWithWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).DealWithWithdraw(ctx, req.(*DealWithWithdrawReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_QueryUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).QueryUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_QueryUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).QueryUserBalance(ctx, req.(*QueryUserBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_QueryGameBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGameBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).QueryGameBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_QueryGameBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).QueryGameBalance(ctx, req.(*QueryGameBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_ManualUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManualUserBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).ManualUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_ManualUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).ManualUserBalance(ctx, req.(*ManualUserBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Balance_ServiceDesc is the grpc.ServiceDesc for Balance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Balance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "balance.Balance",
	HandlerType: (*BalanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalanceChanges",
			Handler:    _Balance_GetBalanceChanges_Handler,
		},
		{
			MethodName: "GetRechargePayments",
			Handler:    _Balance_GetRechargePayments_Handler,
		},
		{
			MethodName: "GetRechargeManuals",
			Handler:    _Balance_GetRechargeManuals_Handler,
		},
		{
			MethodName: "ConfirmPaymentOrder",
			Handler:    _Balance_ConfirmPaymentOrder_Handler,
		},
		{
			MethodName: "GetWithdraws",
			Handler:    _Balance_GetWithdraws_Handler,
		},
		{
			MethodName: "GetWithdrawManuals",
			Handler:    _Balance_GetWithdrawManuals_Handler,
		},
		{
			MethodName: "GetWithdrawReview",
			Handler:    _Balance_GetWithdrawReview_Handler,
		},
		{
			MethodName: "DealWithWithdraw",
			Handler:    _Balance_DealWithWithdraw_Handler,
		},
		{
			MethodName: "QueryUserBalance",
			Handler:    _Balance_QueryUserBalance_Handler,
		},
		{
			MethodName: "QueryGameBalance",
			Handler:    _Balance_QueryGameBalance_Handler,
		},
		{
			MethodName: "ManualUserBalance",
			Handler:    _Balance_ManualUserBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/balance/v1/balance.proto",
}
