// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/balance/v1/balance.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取账变记录请求
type GetBalanceChangesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username" dc:"用户名 (可选)"`                                   // 用户名 (可选)
	ChangeType    int32                  `protobuf:"varint,2,opt,name=change_type,json=changeType,proto3" json:"change_type" dc:"账变类型 1=入款 2=出款 (可选)"` // 账变类型 1=入款 2=出款 (可选)
	TradeType     int32                  `protobuf:"varint,3,opt,name=trade_type,json=tradeType,proto3" json:"trade_type" dc:"交易类型 (可选)"`              // 交易类型 (可选)
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time" dc:"开始时间 (可选)"`               // 开始时间 (可选)
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time" dc:"结束时间 (可选)"`                     // 结束时间 (可选)
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page" dc:"页码"`                                                // 页码
	Size          int32                  `protobuf:"varint,7,opt,name=size,proto3" json:"size" dc:"每页数量"`                                              // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceChangesReq) Reset() {
	*x = GetBalanceChangesReq{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceChangesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceChangesReq) ProtoMessage() {}

func (x *GetBalanceChangesReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceChangesReq.ProtoReflect.Descriptor instead.
func (*GetBalanceChangesReq) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceChangesReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetBalanceChangesReq) GetChangeType() int32 {
	if x != nil {
		return x.ChangeType
	}
	return 0
}

func (x *GetBalanceChangesReq) GetTradeType() int32 {
	if x != nil {
		return x.TradeType
	}
	return 0
}

func (x *GetBalanceChangesReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetBalanceChangesReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetBalanceChangesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBalanceChangesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 账变记录信息
type BalanceChangeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"ID"`                                                 // ID
	TradeType     int32                  `protobuf:"varint,2,opt,name=trade_type,json=tradeType,proto3" json:"trade_type" dc:"交易类型"`                // 交易类型
	TradeTypeName string                 `protobuf:"bytes,3,opt,name=trade_type_name,json=tradeTypeName,proto3" json:"trade_type_name" dc:"交易类型名称"` // 交易类型名称
	UserId        int32                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id" dc:"用户ID"`                         // 用户ID
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username" dc:"用户名"`                                     // 用户名
	TradeNo       string                 `protobuf:"bytes,6,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no" dc:"流水号"`                        // 流水号
	BalanceOld    float64                `protobuf:"fixed64,7,opt,name=balance_old,json=balanceOld,proto3" json:"balance_old" dc:"旧余额"`             // 旧余额
	Money         float64                `protobuf:"fixed64,8,opt,name=money,proto3" json:"money" dc:"变动金额"`                                        // 变动金额
	BalanceNew    float64                `protobuf:"fixed64,9,opt,name=balance_new,json=balanceNew,proto3" json:"balance_new" dc:"新余额"`             // 新余额
	BalanceFrozen float64                `protobuf:"fixed64,10,opt,name=balance_frozen,json=balanceFrozen,proto3" json:"balance_frozen" dc:"冻结余额"`  // 冻结余额
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status" dc:"状态"`                                        // 状态
	StatusName    string                 `protobuf:"bytes,12,opt,name=status_name,json=statusName,proto3" json:"status_name" dc:"状态名称"`             // 状态名称
	Remark        string                 `protobuf:"bytes,13,opt,name=remark,proto3" json:"remark" dc:"备注"`                                         // 备注
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at" dc:"创建时间"`                // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceChangeInfo) Reset() {
	*x = BalanceChangeInfo{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceChangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceChangeInfo) ProtoMessage() {}

func (x *BalanceChangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceChangeInfo.ProtoReflect.Descriptor instead.
func (*BalanceChangeInfo) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceChangeInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BalanceChangeInfo) GetTradeType() int32 {
	if x != nil {
		return x.TradeType
	}
	return 0
}

func (x *BalanceChangeInfo) GetTradeTypeName() string {
	if x != nil {
		return x.TradeTypeName
	}
	return ""
}

func (x *BalanceChangeInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BalanceChangeInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BalanceChangeInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *BalanceChangeInfo) GetBalanceOld() float64 {
	if x != nil {
		return x.BalanceOld
	}
	return 0
}

func (x *BalanceChangeInfo) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *BalanceChangeInfo) GetBalanceNew() float64 {
	if x != nil {
		return x.BalanceNew
	}
	return 0
}

func (x *BalanceChangeInfo) GetBalanceFrozen() float64 {
	if x != nil {
		return x.BalanceFrozen
	}
	return 0
}

func (x *BalanceChangeInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BalanceChangeInfo) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *BalanceChangeInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BalanceChangeInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 获取账变记录响应
type GetBalanceChangesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BalanceChangeInfo   `protobuf:"bytes,1,rep,name=list,proto3" json:"list" dc:"账变记录列表"` // 账变记录列表
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count" dc:"总数量"` // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceChangesRes) Reset() {
	*x = GetBalanceChangesRes{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceChangesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceChangesRes) ProtoMessage() {}

func (x *GetBalanceChangesRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceChangesRes.ProtoReflect.Descriptor instead.
func (*GetBalanceChangesRes) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceChangesRes) GetList() []*BalanceChangeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetBalanceChangesRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取充值记录请求
type GetRechargePaymentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username" dc:"用户名 (可选)"`                      // 用户名 (可选)
	Gateway       int32                  `protobuf:"varint,2,opt,name=gateway,proto3" json:"gateway" dc:"网关类型 (可选)"`                      // 网关类型 (可选)
	PaymentId     int32                  `protobuf:"varint,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id" dc:"支付ID (可选)"` // 支付ID (可选)
	AccountId     int32                  `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id" dc:"账号ID (可选)"` // 账号ID (可选)
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status" dc:"状态 (可选)"`                          // 状态 (可选)
	TradeNo       string                 `protobuf:"bytes,6,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no" dc:"流水号 (可选)"`         // 流水号 (可选)
	Domain        string                 `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain" dc:"域名 (可选)"`                           // 域名 (可选)
	StartTime     string                 `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time" dc:"开始时间 (可选)"`  // 开始时间 (可选)
	EndTime       string                 `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time" dc:"结束时间 (可选)"`        // 结束时间 (可选)
	Page          int32                  `protobuf:"varint,10,opt,name=page,proto3" json:"page" dc:"页码"`                                  // 页码
	Size          int32                  `protobuf:"varint,11,opt,name=size,proto3" json:"size" dc:"每页数量"`                                // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRechargePaymentsReq) Reset() {
	*x = GetRechargePaymentsReq{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRechargePaymentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRechargePaymentsReq) ProtoMessage() {}

func (x *GetRechargePaymentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRechargePaymentsReq.ProtoReflect.Descriptor instead.
func (*GetRechargePaymentsReq) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{3}
}

func (x *GetRechargePaymentsReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetRechargePaymentsReq) GetGateway() int32 {
	if x != nil {
		return x.Gateway
	}
	return 0
}

func (x *GetRechargePaymentsReq) GetPaymentId() int32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *GetRechargePaymentsReq) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetRechargePaymentsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRechargePaymentsReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *GetRechargePaymentsReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetRechargePaymentsReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetRechargePaymentsReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetRechargePaymentsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRechargePaymentsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 充值记录信息
type RechargePaymentInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"ID"`                                                                 // ID
	UserId             int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id" dc:"用户ID"`                                         // 用户ID
	Username           string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username" dc:"用户名"`                                                     // 用户名
	ActivityRechargeId int32                  `protobuf:"varint,4,opt,name=activity_recharge_id,json=activityRechargeId,proto3" json:"activity_recharge_id" dc:"充值活动ID"` // 充值活动ID
	Gateway            int32                  `protobuf:"varint,5,opt,name=gateway,proto3" json:"gateway" dc:"网关类型"`                                                     // 网关类型
	GatewayName        string                 `protobuf:"bytes,6,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name" dc:"网关名称"`                           // 网关名称
	PaymentId          int32                  `protobuf:"varint,7,opt,name=payment_id,json=paymentId,proto3" json:"payment_id" dc:"支付ID"`                                // 支付ID
	PaymentName        string                 `protobuf:"bytes,8,opt,name=payment_name,json=paymentName,proto3" json:"payment_name" dc:"支付名称"`                           // 支付名称
	PaymentAccountId   int32                  `protobuf:"varint,9,opt,name=payment_account_id,json=paymentAccountId,proto3" json:"payment_account_id" dc:"支付账号ID"`       // 支付账号ID
	BankValue          string                 `protobuf:"bytes,10,opt,name=bank_value,json=bankValue,proto3" json:"bank_value" dc:"银行代码"`                                // 银行代码
	TradeNo            string                 `protobuf:"bytes,11,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no" dc:"流水号"`                                       // 流水号
	Money              float64                `protobuf:"fixed64,12,opt,name=money,proto3" json:"money" dc:"充值金额"`                                                       // 充值金额
	Fee                float64                `protobuf:"fixed64,13,opt,name=fee,proto3" json:"fee" dc:"手续费"`                                                            // 手续费
	Status             int32                  `protobuf:"varint,14,opt,name=status,proto3" json:"status" dc:"状态"`                                                        // 状态
	StatusName         string                 `protobuf:"bytes,15,opt,name=status_name,json=statusName,proto3" json:"status_name" dc:"状态名称"`                             // 状态名称
	AdminId            int32                  `protobuf:"varint,16,opt,name=admin_id,json=adminId,proto3" json:"admin_id" dc:"管理员ID"`                                    // 管理员ID
	AdminName          string                 `protobuf:"bytes,17,opt,name=admin_name,json=adminName,proto3" json:"admin_name" dc:"管理员名称"`                               // 管理员名称
	Remark             string                 `protobuf:"bytes,18,opt,name=remark,proto3" json:"remark" dc:"备注"`                                                         // 备注
	CreatedAt          string                 `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at" dc:"创建时间"`                                // 创建时间
	UpdatedAt          string                 `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at" dc:"更新时间"`                                // 更新时间
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RechargePaymentInfo) Reset() {
	*x = RechargePaymentInfo{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargePaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargePaymentInfo) ProtoMessage() {}

func (x *RechargePaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargePaymentInfo.ProtoReflect.Descriptor instead.
func (*RechargePaymentInfo) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{4}
}

func (x *RechargePaymentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RechargePaymentInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RechargePaymentInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RechargePaymentInfo) GetActivityRechargeId() int32 {
	if x != nil {
		return x.ActivityRechargeId
	}
	return 0
}

func (x *RechargePaymentInfo) GetGateway() int32 {
	if x != nil {
		return x.Gateway
	}
	return 0
}

func (x *RechargePaymentInfo) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *RechargePaymentInfo) GetPaymentId() int32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *RechargePaymentInfo) GetPaymentName() string {
	if x != nil {
		return x.PaymentName
	}
	return ""
}

func (x *RechargePaymentInfo) GetPaymentAccountId() int32 {
	if x != nil {
		return x.PaymentAccountId
	}
	return 0
}

func (x *RechargePaymentInfo) GetBankValue() string {
	if x != nil {
		return x.BankValue
	}
	return ""
}

func (x *RechargePaymentInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RechargePaymentInfo) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *RechargePaymentInfo) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *RechargePaymentInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RechargePaymentInfo) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *RechargePaymentInfo) GetAdminId() int32 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *RechargePaymentInfo) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *RechargePaymentInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RechargePaymentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RechargePaymentInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 获取充值记录响应
type GetRechargePaymentsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RechargePaymentInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list" dc:"充值记录列表"` // 充值记录列表
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count" dc:"总数量"` // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRechargePaymentsRes) Reset() {
	*x = GetRechargePaymentsRes{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRechargePaymentsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRechargePaymentsRes) ProtoMessage() {}

func (x *GetRechargePaymentsRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRechargePaymentsRes.ProtoReflect.Descriptor instead.
func (*GetRechargePaymentsRes) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{5}
}

func (x *GetRechargePaymentsRes) GetList() []*RechargePaymentInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetRechargePaymentsRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取后台加款记录请求
type GetRechargeManualsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username" dc:"用户名 (可选)"`                     // 用户名 (可选)
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status" dc:"状态 (可选)"`                         // 状态 (可选)
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time" dc:"开始时间 (可选)"` // 开始时间 (可选)
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time" dc:"结束时间 (可选)"`       // 结束时间 (可选)
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page" dc:"页码"`                                  // 页码
	Size          int32                  `protobuf:"varint,6,opt,name=size,proto3" json:"size" dc:"每页数量"`                                // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRechargeManualsReq) Reset() {
	*x = GetRechargeManualsReq{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRechargeManualsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRechargeManualsReq) ProtoMessage() {}

func (x *GetRechargeManualsReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRechargeManualsReq.ProtoReflect.Descriptor instead.
func (*GetRechargeManualsReq) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{6}
}

func (x *GetRechargeManualsReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetRechargeManualsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRechargeManualsReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetRechargeManualsReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetRechargeManualsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRechargeManualsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 后台加款记录信息
type RechargeManualInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"ID"`                                    // ID
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id" dc:"用户ID"`            // 用户ID
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username" dc:"用户名"`                        // 用户名
	TradeNo       string                 `protobuf:"bytes,4,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no" dc:"流水号"`           // 流水号
	Money         float64                `protobuf:"fixed64,5,opt,name=money,proto3" json:"money" dc:"加款金额"`                           // 加款金额
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status" dc:"状态"`                            // 状态
	StatusName    string                 `protobuf:"bytes,7,opt,name=status_name,json=statusName,proto3" json:"status_name" dc:"状态名称"` // 状态名称
	AdminId       int32                  `protobuf:"varint,8,opt,name=admin_id,json=adminId,proto3" json:"admin_id" dc:"管理员ID"`        // 管理员ID
	AdminName     string                 `protobuf:"bytes,9,opt,name=admin_name,json=adminName,proto3" json:"admin_name" dc:"管理员名称"`   // 管理员名称
	Remark        string                 `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark" dc:"备注"`                            // 备注
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at" dc:"创建时间"`   // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeManualInfo) Reset() {
	*x = RechargeManualInfo{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeManualInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeManualInfo) ProtoMessage() {}

func (x *RechargeManualInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeManualInfo.ProtoReflect.Descriptor instead.
func (*RechargeManualInfo) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{7}
}

func (x *RechargeManualInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RechargeManualInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RechargeManualInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RechargeManualInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RechargeManualInfo) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *RechargeManualInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RechargeManualInfo) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *RechargeManualInfo) GetAdminId() int32 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *RechargeManualInfo) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *RechargeManualInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RechargeManualInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 获取后台加款记录响应
type GetRechargeManualsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RechargeManualInfo  `protobuf:"bytes,1,rep,name=list,proto3" json:"list" dc:"后台加款记录列表"` // 后台加款记录列表
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count" dc:"总数量"`   // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRechargeManualsRes) Reset() {
	*x = GetRechargeManualsRes{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRechargeManualsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRechargeManualsRes) ProtoMessage() {}

func (x *GetRechargeManualsRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRechargeManualsRes.ProtoReflect.Descriptor instead.
func (*GetRechargeManualsRes) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{8}
}

func (x *GetRechargeManualsRes) GetList() []*RechargeManualInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetRechargeManualsRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 确认支付订单请求
type ConfirmPaymentOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"订单ID"`           // 订单ID
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark" dc:"备注 (可选)"` // 备注 (可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentOrderReq) Reset() {
	*x = ConfirmPaymentOrderReq{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentOrderReq) ProtoMessage() {}

func (x *ConfirmPaymentOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentOrderReq.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentOrderReq) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmPaymentOrderReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfirmPaymentOrderReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 确认支付订单响应
type ConfirmPaymentOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success" dc:"是否成功"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message" dc:"响应消息"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentOrderRes) Reset() {
	*x = ConfirmPaymentOrderRes{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentOrderRes) ProtoMessage() {}

func (x *ConfirmPaymentOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentOrderRes.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentOrderRes) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmPaymentOrderRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmPaymentOrderRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取提现记录请求
type GetWithdrawsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username" dc:"用户名 (可选)"`                     // 用户名 (可选)
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status" dc:"状态 (可选)"`                         // 状态 (可选)
	TradeNo       string                 `protobuf:"bytes,3,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no" dc:"流水号 (可选)"`        // 流水号 (可选)
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain" dc:"域名 (可选)"`                          // 域名 (可选)
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time" dc:"开始时间 (可选)"` // 开始时间 (可选)
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time" dc:"结束时间 (可选)"`       // 结束时间 (可选)
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page" dc:"页码"`                                  // 页码
	Size          int32                  `protobuf:"varint,8,opt,name=size,proto3" json:"size" dc:"每页数量"`                                // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawsReq) Reset() {
	*x = GetWithdrawsReq{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawsReq) ProtoMessage() {}

func (x *GetWithdrawsReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawsReq.ProtoReflect.Descriptor instead.
func (*GetWithdrawsReq) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{11}
}

func (x *GetWithdrawsReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetWithdrawsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetWithdrawsReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *GetWithdrawsReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetWithdrawsReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetWithdrawsReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetWithdrawsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetWithdrawsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 提现记录信息
type WithdrawInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"ID"`                                            // ID
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id" dc:"用户ID"`                    // 用户ID
	UserLevelId   int32                  `protobuf:"varint,3,opt,name=user_level_id,json=userLevelId,proto3" json:"user_level_id" dc:"用户层级ID"` // 用户层级ID
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username" dc:"用户名"`                                // 用户名
	TradeNo       string                 `protobuf:"bytes,5,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no" dc:"流水号"`                   // 流水号
	Money         float64                `protobuf:"fixed64,6,opt,name=money,proto3" json:"money" dc:"提现金额"`                                   // 提现金额
	Fee           float64                `protobuf:"fixed64,7,opt,name=fee,proto3" json:"fee" dc:"手续费"`                                        // 手续费
	BankName      string                 `protobuf:"bytes,8,opt,name=bank_name,json=bankName,proto3" json:"bank_name" dc:"银行名称"`               // 银行名称
	CardAccount   string                 `protobuf:"bytes,9,opt,name=card_account,json=cardAccount,proto3" json:"card_account" dc:"银行户名"`      // 银行户名
	CardNo        string                 `protobuf:"bytes,10,opt,name=card_no,json=cardNo,proto3" json:"card_no" dc:"卡号"`                      // 卡号
	DepositBank   string                 `protobuf:"bytes,11,opt,name=deposit_bank,json=depositBank,proto3" json:"deposit_bank" dc:"开户行"`      // 开户行
	Status        int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status" dc:"状态"`                                   // 状态
	StatusName    string                 `protobuf:"bytes,13,opt,name=status_name,json=statusName,proto3" json:"status_name" dc:"状态名称"`        // 状态名称
	AdminId       int32                  `protobuf:"varint,14,opt,name=admin_id,json=adminId,proto3" json:"admin_id" dc:"管理员ID"`               // 管理员ID
	AdminName     string                 `protobuf:"bytes,15,opt,name=admin_name,json=adminName,proto3" json:"admin_name" dc:"管理员名称"`          // 管理员名称
	Remark        string                 `protobuf:"bytes,16,opt,name=remark,proto3" json:"remark" dc:"备注"`                                    // 备注
	CreatedAt     string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at" dc:"创建时间"`           // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at" dc:"更新时间"`           // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawInfo) Reset() {
	*x = WithdrawInfo{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawInfo) ProtoMessage() {}

func (x *WithdrawInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawInfo.ProtoReflect.Descriptor instead.
func (*WithdrawInfo) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{12}
}

func (x *WithdrawInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WithdrawInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawInfo) GetUserLevelId() int32 {
	if x != nil {
		return x.UserLevelId
	}
	return 0
}

func (x *WithdrawInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WithdrawInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *WithdrawInfo) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *WithdrawInfo) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *WithdrawInfo) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *WithdrawInfo) GetCardAccount() string {
	if x != nil {
		return x.CardAccount
	}
	return ""
}

func (x *WithdrawInfo) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *WithdrawInfo) GetDepositBank() string {
	if x != nil {
		return x.DepositBank
	}
	return ""
}

func (x *WithdrawInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WithdrawInfo) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *WithdrawInfo) GetAdminId() int32 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *WithdrawInfo) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *WithdrawInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *WithdrawInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WithdrawInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 获取提现记录响应
type GetWithdrawsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*WithdrawInfo        `protobuf:"bytes,1,rep,name=list,proto3" json:"list" dc:"提现记录列表"` // 提现记录列表
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count" dc:"总数量"` // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawsRes) Reset() {
	*x = GetWithdrawsRes{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawsRes) ProtoMessage() {}

func (x *GetWithdrawsRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawsRes.ProtoReflect.Descriptor instead.
func (*GetWithdrawsRes) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{13}
}

func (x *GetWithdrawsRes) GetList() []*WithdrawInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetWithdrawsRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取后台提现记录请求
type GetWithdrawManualsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username" dc:"用户名 (可选)"`                     // 用户名 (可选)
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status" dc:"状态 (可选)"`                         // 状态 (可选)
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time" dc:"开始时间 (可选)"` // 开始时间 (可选)
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time" dc:"结束时间 (可选)"`       // 结束时间 (可选)
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page" dc:"页码"`                                  // 页码
	Size          int32                  `protobuf:"varint,6,opt,name=size,proto3" json:"size" dc:"每页数量"`                                // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawManualsReq) Reset() {
	*x = GetWithdrawManualsReq{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawManualsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawManualsReq) ProtoMessage() {}

func (x *GetWithdrawManualsReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawManualsReq.ProtoReflect.Descriptor instead.
func (*GetWithdrawManualsReq) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{14}
}

func (x *GetWithdrawManualsReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetWithdrawManualsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetWithdrawManualsReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetWithdrawManualsReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetWithdrawManualsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetWithdrawManualsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 后台提现记录信息
type WithdrawManualInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"ID"`                                    // ID
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id" dc:"用户ID"`            // 用户ID
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username" dc:"用户名"`                        // 用户名
	TradeNo       string                 `protobuf:"bytes,4,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no" dc:"流水号"`           // 流水号
	Money         float64                `protobuf:"fixed64,5,opt,name=money,proto3" json:"money" dc:"提现金额"`                           // 提现金额
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status" dc:"状态"`                            // 状态
	StatusName    string                 `protobuf:"bytes,7,opt,name=status_name,json=statusName,proto3" json:"status_name" dc:"状态名称"` // 状态名称
	AdminId       int32                  `protobuf:"varint,8,opt,name=admin_id,json=adminId,proto3" json:"admin_id" dc:"管理员ID"`        // 管理员ID
	AdminName     string                 `protobuf:"bytes,9,opt,name=admin_name,json=adminName,proto3" json:"admin_name" dc:"管理员名称"`   // 管理员名称
	Remark        string                 `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark" dc:"备注"`                            // 备注
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at" dc:"创建时间"`   // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawManualInfo) Reset() {
	*x = WithdrawManualInfo{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawManualInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawManualInfo) ProtoMessage() {}

func (x *WithdrawManualInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawManualInfo.ProtoReflect.Descriptor instead.
func (*WithdrawManualInfo) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{15}
}

func (x *WithdrawManualInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WithdrawManualInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawManualInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WithdrawManualInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *WithdrawManualInfo) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *WithdrawManualInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WithdrawManualInfo) GetStatusName() string {
	if x != nil {
		return x.StatusName
	}
	return ""
}

func (x *WithdrawManualInfo) GetAdminId() int32 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *WithdrawManualInfo) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *WithdrawManualInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *WithdrawManualInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 获取后台提现记录响应
type GetWithdrawManualsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*WithdrawManualInfo  `protobuf:"bytes,1,rep,name=list,proto3" json:"list" dc:"后台提现记录列表"` // 后台提现记录列表
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count" dc:"总数量"`   // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawManualsRes) Reset() {
	*x = GetWithdrawManualsRes{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawManualsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawManualsRes) ProtoMessage() {}

func (x *GetWithdrawManualsRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawManualsRes.ProtoReflect.Descriptor instead.
func (*GetWithdrawManualsRes) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{16}
}

func (x *GetWithdrawManualsRes) GetList() []*WithdrawManualInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetWithdrawManualsRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取提现审核信息请求
type GetWithdrawReviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"提现记录ID"` // 提现记录ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawReviewReq) Reset() {
	*x = GetWithdrawReviewReq{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawReviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawReviewReq) ProtoMessage() {}

func (x *GetWithdrawReviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawReviewReq.ProtoReflect.Descriptor instead.
func (*GetWithdrawReviewReq) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{17}
}

func (x *GetWithdrawReviewReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 提现审核信息
type WithdrawReviewInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"ID"`                                       // ID
	UserId      int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id" dc:"用户ID"`               // 用户ID
	Username    string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username" dc:"用户名"`                           // 用户名
	TradeNo     string                 `protobuf:"bytes,4,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no" dc:"流水号"`              // 流水号
	Money       float64                `protobuf:"fixed64,5,opt,name=money,proto3" json:"money" dc:"提现金额"`                              // 提现金额
	Fee         float64                `protobuf:"fixed64,6,opt,name=fee,proto3" json:"fee" dc:"手续费"`                                   // 手续费
	BankName    string                 `protobuf:"bytes,7,opt,name=bank_name,json=bankName,proto3" json:"bank_name" dc:"银行名称"`          // 银行名称
	CardAccount string                 `protobuf:"bytes,8,opt,name=card_account,json=cardAccount,proto3" json:"card_account" dc:"银行户名"` // 银行户名
	CardNo      string                 `protobuf:"bytes,9,opt,name=card_no,json=cardNo,proto3" json:"card_no" dc:"卡号"`                  // 卡号
	DepositBank string                 `protobuf:"bytes,10,opt,name=deposit_bank,json=depositBank,proto3" json:"deposit_bank" dc:"开户行"` // 开户行
	Status      int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status" dc:"状态"`                              // 状态
	Remark      string                 `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark" dc:"备注"`                               // 备注
	CreatedAt   string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at" dc:"创建时间"`      // 创建时间
	// 用户信息
	UserRealname      string  `protobuf:"bytes,14,opt,name=user_realname,json=userRealname,proto3" json:"user_realname" dc:"用户信息用户真实姓名"`                // 用户真实姓名
	UserMobile        string  `protobuf:"bytes,15,opt,name=user_mobile,json=userMobile,proto3" json:"user_mobile" dc:"用户手机号"`                           // 用户手机号
	UserBalance       float64 `protobuf:"fixed64,16,opt,name=user_balance,json=userBalance,proto3" json:"user_balance" dc:"用户余额"`                       // 用户余额
	UserBalanceFrozen float64 `protobuf:"fixed64,17,opt,name=user_balance_frozen,json=userBalanceFrozen,proto3" json:"user_balance_frozen" dc:"用户冻结余额"` // 用户冻结余额
	// 统计信息
	TotalRecharge float64 `protobuf:"fixed64,18,opt,name=total_recharge,json=totalRecharge,proto3" json:"total_recharge" dc:"统计信息总充值"` // 总充值
	TotalWithdraw float64 `protobuf:"fixed64,19,opt,name=total_withdraw,json=totalWithdraw,proto3" json:"total_withdraw" dc:"总提现"`     // 总提现
	WithdrawCount int32   `protobuf:"varint,20,opt,name=withdraw_count,json=withdrawCount,proto3" json:"withdraw_count" dc:"提现次数"`     // 提现次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawReviewInfo) Reset() {
	*x = WithdrawReviewInfo{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawReviewInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReviewInfo) ProtoMessage() {}

func (x *WithdrawReviewInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReviewInfo.ProtoReflect.Descriptor instead.
func (*WithdrawReviewInfo) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{18}
}

func (x *WithdrawReviewInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WithdrawReviewInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawReviewInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WithdrawReviewInfo) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *WithdrawReviewInfo) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *WithdrawReviewInfo) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *WithdrawReviewInfo) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *WithdrawReviewInfo) GetCardAccount() string {
	if x != nil {
		return x.CardAccount
	}
	return ""
}

func (x *WithdrawReviewInfo) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *WithdrawReviewInfo) GetDepositBank() string {
	if x != nil {
		return x.DepositBank
	}
	return ""
}

func (x *WithdrawReviewInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WithdrawReviewInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *WithdrawReviewInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WithdrawReviewInfo) GetUserRealname() string {
	if x != nil {
		return x.UserRealname
	}
	return ""
}

func (x *WithdrawReviewInfo) GetUserMobile() string {
	if x != nil {
		return x.UserMobile
	}
	return ""
}

func (x *WithdrawReviewInfo) GetUserBalance() float64 {
	if x != nil {
		return x.UserBalance
	}
	return 0
}

func (x *WithdrawReviewInfo) GetUserBalanceFrozen() float64 {
	if x != nil {
		return x.UserBalanceFrozen
	}
	return 0
}

func (x *WithdrawReviewInfo) GetTotalRecharge() float64 {
	if x != nil {
		return x.TotalRecharge
	}
	return 0
}

func (x *WithdrawReviewInfo) GetTotalWithdraw() float64 {
	if x != nil {
		return x.TotalWithdraw
	}
	return 0
}

func (x *WithdrawReviewInfo) GetWithdrawCount() int32 {
	if x != nil {
		return x.WithdrawCount
	}
	return 0
}

// 获取提现审核信息响应
type GetWithdrawReviewRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *WithdrawReviewInfo    `protobuf:"bytes,1,opt,name=data,proto3" json:"data" dc:"审核信息"` // 审核信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawReviewRes) Reset() {
	*x = GetWithdrawReviewRes{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawReviewRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawReviewRes) ProtoMessage() {}

func (x *GetWithdrawReviewRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawReviewRes.ProtoReflect.Descriptor instead.
func (*GetWithdrawReviewRes) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{19}
}

func (x *GetWithdrawReviewRes) GetData() *WithdrawReviewInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 处理提现请求
type DealWithWithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"提现记录ID"`                  // 提现记录ID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type" dc:"处理类型 1=确认 0=拒绝 2=补单"` // 处理类型 1=确认 0=拒绝 2=补单
	Fee           float64                `protobuf:"fixed64,3,opt,name=fee,proto3" json:"fee" dc:"手续费 (可选)"`             // 手续费 (可选)
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark" dc:"备注 (可选)"`          // 备注 (可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealWithWithdrawReq) Reset() {
	*x = DealWithWithdrawReq{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealWithWithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealWithWithdrawReq) ProtoMessage() {}

func (x *DealWithWithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealWithWithdrawReq.ProtoReflect.Descriptor instead.
func (*DealWithWithdrawReq) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{20}
}

func (x *DealWithWithdrawReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DealWithWithdrawReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DealWithWithdrawReq) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *DealWithWithdrawReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 处理提现响应
type DealWithWithdrawRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success" dc:"是否成功"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message" dc:"响应消息"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealWithWithdrawRes) Reset() {
	*x = DealWithWithdrawRes{}
	mi := &file_backend_balance_v1_balance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealWithWithdrawRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealWithWithdrawRes) ProtoMessage() {}

func (x *DealWithWithdrawRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_balance_v1_balance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealWithWithdrawRes.ProtoReflect.Descriptor instead.
func (*DealWithWithdrawRes) Descriptor() ([]byte, []int) {
	return file_backend_balance_v1_balance_proto_rawDescGZIP(), []int{21}
}

func (x *DealWithWithdrawRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DealWithWithdrawRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_backend_balance_v1_balance_proto protoreflect.FileDescriptor

const file_backend_balance_v1_balance_proto_rawDesc = "" +
	"\n" +
	" backend/balance/v1/balance.proto\x12\abalance\"\xd4\x01\n" +
	"\x14GetBalanceChangesReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vchange_type\x18\x02 \x01(\x05R\n" +
	"changeType\x12\x1d\n" +
	"\n" +
	"trade_type\x18\x03 \x01(\x05R\ttradeType\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\a \x01(\x05R\x04size\"\xa9\x03\n" +
	"\x11BalanceChangeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"trade_type\x18\x02 \x01(\x05R\ttradeType\x12&\n" +
	"\x0ftrade_type_name\x18\x03 \x01(\tR\rtradeTypeName\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x19\n" +
	"\btrade_no\x18\x06 \x01(\tR\atradeNo\x12\x1f\n" +
	"\vbalance_old\x18\a \x01(\x01R\n" +
	"balanceOld\x12\x14\n" +
	"\x05money\x18\b \x01(\x01R\x05money\x12\x1f\n" +
	"\vbalance_new\x18\t \x01(\x01R\n" +
	"balanceNew\x12%\n" +
	"\x0ebalance_frozen\x18\n" +
	" \x01(\x01R\rbalanceFrozen\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\f \x01(\tR\n" +
	"statusName\x12\x16\n" +
	"\x06remark\x18\r \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\"\\\n" +
	"\x14GetBalanceChangesRes\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.balance.BalanceChangeInfoR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xb9\x02\n" +
	"\x16GetRechargePaymentsReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\agateway\x18\x02 \x01(\x05R\agateway\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\x05R\tpaymentId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\x05R\taccountId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x19\n" +
	"\btrade_no\x18\x06 \x01(\tR\atradeNo\x12\x16\n" +
	"\x06domain\x18\a \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\tR\aendTime\x12\x12\n" +
	"\x04page\x18\n" +
	" \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\v \x01(\x05R\x04size\"\xe4\x04\n" +
	"\x13RechargePaymentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x120\n" +
	"\x14activity_recharge_id\x18\x04 \x01(\x05R\x12activityRechargeId\x12\x18\n" +
	"\agateway\x18\x05 \x01(\x05R\agateway\x12!\n" +
	"\fgateway_name\x18\x06 \x01(\tR\vgatewayName\x12\x1d\n" +
	"\n" +
	"payment_id\x18\a \x01(\x05R\tpaymentId\x12!\n" +
	"\fpayment_name\x18\b \x01(\tR\vpaymentName\x12,\n" +
	"\x12payment_account_id\x18\t \x01(\x05R\x10paymentAccountId\x12\x1d\n" +
	"\n" +
	"bank_value\x18\n" +
	" \x01(\tR\tbankValue\x12\x19\n" +
	"\btrade_no\x18\v \x01(\tR\atradeNo\x12\x14\n" +
	"\x05money\x18\f \x01(\x01R\x05money\x12\x10\n" +
	"\x03fee\x18\r \x01(\x01R\x03fee\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\x0f \x01(\tR\n" +
	"statusName\x12\x19\n" +
	"\badmin_id\x18\x10 \x01(\x05R\aadminId\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x11 \x01(\tR\tadminName\x12\x16\n" +
	"\x06remark\x18\x12 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\x13 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\tR\tupdatedAt\"`\n" +
	"\x16GetRechargePaymentsRes\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.balance.RechargePaymentInfoR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xad\x01\n" +
	"\x15GetRechargeManualsReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x05R\x04size\"\xb4\x02\n" +
	"\x12RechargeManualInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x19\n" +
	"\btrade_no\x18\x04 \x01(\tR\atradeNo\x12\x14\n" +
	"\x05money\x18\x05 \x01(\x01R\x05money\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\a \x01(\tR\n" +
	"statusName\x12\x19\n" +
	"\badmin_id\x18\b \x01(\x05R\aadminId\x12\x1d\n" +
	"\n" +
	"admin_name\x18\t \x01(\tR\tadminName\x12\x16\n" +
	"\x06remark\x18\n" +
	" \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"^\n" +
	"\x15GetRechargeManualsRes\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.balance.RechargeManualInfoR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"@\n" +
	"\x16ConfirmPaymentOrderReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\"L\n" +
	"\x16ConfirmPaymentOrderRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xda\x01\n" +
	"\x0fGetWithdrawsReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x19\n" +
	"\btrade_no\x18\x03 \x01(\tR\atradeNo\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\b \x01(\x05R\x04size\"\xff\x03\n" +
	"\fWithdrawInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\"\n" +
	"\ruser_level_id\x18\x03 \x01(\x05R\vuserLevelId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x19\n" +
	"\btrade_no\x18\x05 \x01(\tR\atradeNo\x12\x14\n" +
	"\x05money\x18\x06 \x01(\x01R\x05money\x12\x10\n" +
	"\x03fee\x18\a \x01(\x01R\x03fee\x12\x1b\n" +
	"\tbank_name\x18\b \x01(\tR\bbankName\x12!\n" +
	"\fcard_account\x18\t \x01(\tR\vcardAccount\x12\x17\n" +
	"\acard_no\x18\n" +
	" \x01(\tR\x06cardNo\x12!\n" +
	"\fdeposit_bank\x18\v \x01(\tR\vdepositBank\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\r \x01(\tR\n" +
	"statusName\x12\x19\n" +
	"\badmin_id\x18\x0e \x01(\x05R\aadminId\x12\x1d\n" +
	"\n" +
	"admin_name\x18\x0f \x01(\tR\tadminName\x12\x16\n" +
	"\x06remark\x18\x10 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\tR\tupdatedAt\"R\n" +
	"\x0fGetWithdrawsRes\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.balance.WithdrawInfoR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xad\x01\n" +
	"\x15GetWithdrawManualsReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x05R\x04size\"\xb4\x02\n" +
	"\x12WithdrawManualInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x19\n" +
	"\btrade_no\x18\x04 \x01(\tR\atradeNo\x12\x14\n" +
	"\x05money\x18\x05 \x01(\x01R\x05money\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_name\x18\a \x01(\tR\n" +
	"statusName\x12\x19\n" +
	"\badmin_id\x18\b \x01(\x05R\aadminId\x12\x1d\n" +
	"\n" +
	"admin_name\x18\t \x01(\tR\tadminName\x12\x16\n" +
	"\x06remark\x18\n" +
	" \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"^\n" +
	"\x15GetWithdrawManualsRes\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.balance.WithdrawManualInfoR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"&\n" +
	"\x14GetWithdrawReviewReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xf5\x04\n" +
	"\x12WithdrawReviewInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x19\n" +
	"\btrade_no\x18\x04 \x01(\tR\atradeNo\x12\x14\n" +
	"\x05money\x18\x05 \x01(\x01R\x05money\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x01R\x03fee\x12\x1b\n" +
	"\tbank_name\x18\a \x01(\tR\bbankName\x12!\n" +
	"\fcard_account\x18\b \x01(\tR\vcardAccount\x12\x17\n" +
	"\acard_no\x18\t \x01(\tR\x06cardNo\x12!\n" +
	"\fdeposit_bank\x18\n" +
	" \x01(\tR\vdepositBank\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\f \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12#\n" +
	"\ruser_realname\x18\x0e \x01(\tR\fuserRealname\x12\x1f\n" +
	"\vuser_mobile\x18\x0f \x01(\tR\n" +
	"userMobile\x12!\n" +
	"\fuser_balance\x18\x10 \x01(\x01R\vuserBalance\x12.\n" +
	"\x13user_balance_frozen\x18\x11 \x01(\x01R\x11userBalanceFrozen\x12%\n" +
	"\x0etotal_recharge\x18\x12 \x01(\x01R\rtotalRecharge\x12%\n" +
	"\x0etotal_withdraw\x18\x13 \x01(\x01R\rtotalWithdraw\x12%\n" +
	"\x0ewithdraw_count\x18\x14 \x01(\x05R\rwithdrawCount\"G\n" +
	"\x14GetWithdrawReviewRes\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.balance.WithdrawReviewInfoR\x04data\"c\n" +
	"\x13DealWithWithdrawReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x10\n" +
	"\x03fee\x18\x03 \x01(\x01R\x03fee\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"I\n" +
	"\x13DealWithWithdrawRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb1\x05\n" +
	"\aBalance\x12S\n" +
	"\x11GetBalanceChanges\x12\x1d.balance.GetBalanceChangesReq\x1a\x1d.balance.GetBalanceChangesRes\"\x00\x12Y\n" +
	"\x13GetRechargePayments\x12\x1f.balance.GetRechargePaymentsReq\x1a\x1f.balance.GetRechargePaymentsRes\"\x00\x12V\n" +
	"\x12GetRechargeManuals\x12\x1e.balance.GetRechargeManualsReq\x1a\x1e.balance.GetRechargeManualsRes\"\x00\x12Y\n" +
	"\x13ConfirmPaymentOrder\x12\x1f.balance.ConfirmPaymentOrderReq\x1a\x1f.balance.ConfirmPaymentOrderRes\"\x00\x12D\n" +
	"\fGetWithdraws\x12\x18.balance.GetWithdrawsReq\x1a\x18.balance.GetWithdrawsRes\"\x00\x12V\n" +
	"\x12GetWithdrawManuals\x12\x1e.balance.GetWithdrawManualsReq\x1a\x1e.balance.GetWithdrawManualsRes\"\x00\x12S\n" +
	"\x11GetWithdrawReview\x12\x1d.balance.GetWithdrawReviewReq\x1a\x1d.balance.GetWithdrawReviewRes\"\x00\x12P\n" +
	"\x10DealWithWithdraw\x12\x1c.balance.DealWithWithdrawReq\x1a\x1c.balance.DealWithWithdrawRes\"\x00B+Z)jh_balance_service/api/backend/balance/v1b\x06proto3"

var (
	file_backend_balance_v1_balance_proto_rawDescOnce sync.Once
	file_backend_balance_v1_balance_proto_rawDescData []byte
)

func file_backend_balance_v1_balance_proto_rawDescGZIP() []byte {
	file_backend_balance_v1_balance_proto_rawDescOnce.Do(func() {
		file_backend_balance_v1_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_balance_v1_balance_proto_rawDesc), len(file_backend_balance_v1_balance_proto_rawDesc)))
	})
	return file_backend_balance_v1_balance_proto_rawDescData
}

var file_backend_balance_v1_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_backend_balance_v1_balance_proto_goTypes = []any{
	(*GetBalanceChangesReq)(nil),   // 0: balance.GetBalanceChangesReq
	(*BalanceChangeInfo)(nil),      // 1: balance.BalanceChangeInfo
	(*GetBalanceChangesRes)(nil),   // 2: balance.GetBalanceChangesRes
	(*GetRechargePaymentsReq)(nil), // 3: balance.GetRechargePaymentsReq
	(*RechargePaymentInfo)(nil),    // 4: balance.RechargePaymentInfo
	(*GetRechargePaymentsRes)(nil), // 5: balance.GetRechargePaymentsRes
	(*GetRechargeManualsReq)(nil),  // 6: balance.GetRechargeManualsReq
	(*RechargeManualInfo)(nil),     // 7: balance.RechargeManualInfo
	(*GetRechargeManualsRes)(nil),  // 8: balance.GetRechargeManualsRes
	(*ConfirmPaymentOrderReq)(nil), // 9: balance.ConfirmPaymentOrderReq
	(*ConfirmPaymentOrderRes)(nil), // 10: balance.ConfirmPaymentOrderRes
	(*GetWithdrawsReq)(nil),        // 11: balance.GetWithdrawsReq
	(*WithdrawInfo)(nil),           // 12: balance.WithdrawInfo
	(*GetWithdrawsRes)(nil),        // 13: balance.GetWithdrawsRes
	(*GetWithdrawManualsReq)(nil),  // 14: balance.GetWithdrawManualsReq
	(*WithdrawManualInfo)(nil),     // 15: balance.WithdrawManualInfo
	(*GetWithdrawManualsRes)(nil),  // 16: balance.GetWithdrawManualsRes
	(*GetWithdrawReviewReq)(nil),   // 17: balance.GetWithdrawReviewReq
	(*WithdrawReviewInfo)(nil),     // 18: balance.WithdrawReviewInfo
	(*GetWithdrawReviewRes)(nil),   // 19: balance.GetWithdrawReviewRes
	(*DealWithWithdrawReq)(nil),    // 20: balance.DealWithWithdrawReq
	(*DealWithWithdrawRes)(nil),    // 21: balance.DealWithWithdrawRes
}
var file_backend_balance_v1_balance_proto_depIdxs = []int32{
	1,  // 0: balance.GetBalanceChangesRes.list:type_name -> balance.BalanceChangeInfo
	4,  // 1: balance.GetRechargePaymentsRes.list:type_name -> balance.RechargePaymentInfo
	7,  // 2: balance.GetRechargeManualsRes.list:type_name -> balance.RechargeManualInfo
	12, // 3: balance.GetWithdrawsRes.list:type_name -> balance.WithdrawInfo
	15, // 4: balance.GetWithdrawManualsRes.list:type_name -> balance.WithdrawManualInfo
	18, // 5: balance.GetWithdrawReviewRes.data:type_name -> balance.WithdrawReviewInfo
	0,  // 6: balance.Balance.GetBalanceChanges:input_type -> balance.GetBalanceChangesReq
	3,  // 7: balance.Balance.GetRechargePayments:input_type -> balance.GetRechargePaymentsReq
	6,  // 8: balance.Balance.GetRechargeManuals:input_type -> balance.GetRechargeManualsReq
	9,  // 9: balance.Balance.ConfirmPaymentOrder:input_type -> balance.ConfirmPaymentOrderReq
	11, // 10: balance.Balance.GetWithdraws:input_type -> balance.GetWithdrawsReq
	14, // 11: balance.Balance.GetWithdrawManuals:input_type -> balance.GetWithdrawManualsReq
	17, // 12: balance.Balance.GetWithdrawReview:input_type -> balance.GetWithdrawReviewReq
	20, // 13: balance.Balance.DealWithWithdraw:input_type -> balance.DealWithWithdrawReq
	2,  // 14: balance.Balance.GetBalanceChanges:output_type -> balance.GetBalanceChangesRes
	5,  // 15: balance.Balance.GetRechargePayments:output_type -> balance.GetRechargePaymentsRes
	8,  // 16: balance.Balance.GetRechargeManuals:output_type -> balance.GetRechargeManualsRes
	10, // 17: balance.Balance.ConfirmPaymentOrder:output_type -> balance.ConfirmPaymentOrderRes
	13, // 18: balance.Balance.GetWithdraws:output_type -> balance.GetWithdrawsRes
	16, // 19: balance.Balance.GetWithdrawManuals:output_type -> balance.GetWithdrawManualsRes
	19, // 20: balance.Balance.GetWithdrawReview:output_type -> balance.GetWithdrawReviewRes
	21, // 21: balance.Balance.DealWithWithdraw:output_type -> balance.DealWithWithdrawRes
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_backend_balance_v1_balance_proto_init() }
func file_backend_balance_v1_balance_proto_init() {
	if File_backend_balance_v1_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_balance_v1_balance_proto_rawDesc), len(file_backend_balance_v1_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_balance_v1_balance_proto_goTypes,
		DependencyIndexes: file_backend_balance_v1_balance_proto_depIdxs,
		MessageInfos:      file_backend_balance_v1_balance_proto_msgTypes,
	}.Build()
	File_backend_balance_v1_balance_proto = out.File
	file_backend_balance_v1_balance_proto_goTypes = nil
	file_backend_balance_v1_balance_proto_depIdxs = nil
}
